import { chromium } from 'playwright-core'; import http from 'http'; import fs from 'fs';
const types={'.js':'text/javascript','.css':'text/css','.html':'text/html'};
const srv = http.createServer((q, r) => { let u=decodeURIComponent(q.url.split('?')[0]); const f='.'+u; try { const e=f.slice(f.lastIndexOf('.')); r.setHeader('content-type',types[e]||'application/octet-stream'); r.end(fs.readFileSync(f)); } catch { r.statusCode = 404; r.end(); } }).listen(8164);
const b = await chromium.launch({ ...(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {}), args: ['--no-sandbox'] });
const USER = new URL('../../userscript/katastar-gps-rs.user.js', import.meta.url).pathname;
const fails = []; const note = (ok, msg) => { if (!ok) fails.push(msg); console.log(ok ? '  ok  ' : '  FAIL', msg); };
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', 'base64');
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, permissions: ['geolocation'], geolocation: { latitude: 44.73045, longitude: 18.0807, accuracy: 4 } });
const p = await ctx.newPage(); p.errs = []; p.on('pageerror', e => p.errs.push(e.message));
let geo = null;
await p.route(/\/wms\?/, r => /GetFeatureInfo/i.test(r.request().url()) ? r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(geo) }) : r.fulfill({ status: 200, contentType: 'image/png', body: PNG }));
await p.goto('http://localhost:8164/ekatastar-wms.html'); await p.addScriptTag({ path: USER }); await p.waitForTimeout(900);
console.log('1) POCETNA');
await p.screenshot({ path: 'home.png' });
const home = await p.evaluate(() => { const q = (s) => document.querySelector(s), r = (e) => e && e.getBoundingClientRect(); const d = q('#d_all');
  return { head: q('#kgrs-head') && q('#kgrs-head').innerText, hero: !!q('#kgrs-mapbtn'), sh: q('#kgrs-sh') && q('#kgrs-sh').innerText, foot: q('#kgrs-foot') && q('#kgrs-foot').innerText,
    order: [q('#kgrs-head'), q('#kgrs-mapbtn'), q('#kgrs-sh'), q('#d_all .ui.pointing.menu')].map(e => e ? Math.round(r(e).top) : -1), hx: document.documentElement.scrollWidth > innerWidth,
    footBottom: Math.round(r(q('#kgrs-foot')).bottom), vh: innerHeight, headCenter: Math.round((r(q('#kgrs-head svg')).left + r(q('#kgrs-head .hd-tx')).right) / 2), intro: [...document.querySelectorAll('#content_m h2')].filter(h => getComputedStyle(h).display !== 'none' && h.offsetParent).map(h => h.innerText) }; });
console.log(JSON.stringify(home));
note(/Katastar/.test(home.head) && /Developed by 277DIGITAL.COM/.test(home.foot) && home.hero && /Pretraga po broju parcele/.test(home.sh), 'zaglavlje, hero, naslov pretrage, podnozje postoje');
note(home.order[0] < home.order[1] && home.order[1] < home.order[2] && home.order[2] < home.order[3] && home.order.every(x => x >= 0), 'redoslijed: header < mapa < naslov pretrage < polja: ' + home.order);
note(Math.abs(home.headCenter - 195) < 24, 'naslov je na sredini (' + home.headCenter + ')');
note(/Developed by 277DIGITAL.COM/.test(await p.evaluate(() => document.querySelector('#kgrs-head').innerText)), 'header ima Developed by 277DIGITAL.COM');
const lat = await p.evaluate(() => ({ t: document.querySelector('#d_all .ui.pointing.menu').innerText, lbl: [...document.querySelectorAll('#d_all form label')].map(l => l.innerText).join('|'), btn: document.getElementById('btnKC').innerText, cyr: [...document.querySelectorAll('#d_all form label, #d_all .ui.pointing.menu .item, #btnKC')].some(e => /[\u0400-\u04FF]/.test(e.innerText)) }));
console.log(JSON.stringify(lat));
note(!lat.cyr && /Po parceli/.test(lat.t) && /Pretraži/.test(lat.btn), 'forma pretrage je na latinici');
note(!home.hx, 'nema horizontalnog skrola');
console.log('2) OTVARANJE MAPE: auto-lociranje');
const ll = await p.evaluate(() => ol.proj.transform([18.0807, 44.73045], 'EPSG:4326', map.getView().getProjection()));
const R = (dx0, dy0, dx1, dy1) => [[ll[0] + dx0, ll[1] + dy0], [ll[0] + dx1, ll[1] + dy0], [ll[0] + dx1, ll[1] + dy1], [ll[0] + dx0, ll[1] + dy1], [ll[0] + dx0, ll[1] + dy0]];
geo = { type: 'FeatureCollection', features: [{ type: 'Feature', geometry: { type: 'Polygon', coordinates: [R(-12.3, -8, 20, 14)] }, properties: { POVRSINA: '715', KULTURA: 'Njiva 3. klase', KO_NAZIV: 'Doboj' } }] };
await p.click('#kgrs-mapbtn'); await p.waitForTimeout(300);
note(await p.evaluate(() => { const l = document.getElementById('kgrs-load'); return !!l && !l.classList.contains('off') && /Učitavam/.test(l.innerText); }), 'loader se prikazuje dok se mapa učitava');
await p.waitForTimeout(6000);
console.log(await p.evaluate(() => { const l = document.getElementById('kgrs-load'); return l ? l.className + '|' + document.querySelectorAll('#kgrs-load').length : 'gone'; }));
note(await p.evaluate(() => { const l = document.getElementById('kgrs-load'); return !l || l.classList.contains('off'); }), 'loader nestaje kad je mapa spremna');
const st = await p.evaluate(() => ({ on: document.getElementById('kgrs').classList.contains('on'), go: document.querySelector('#kgrs .go').className, st: document.querySelector('#kgrs .st').innerText.replace(/\n/g, ' | '), res: map.getView().getResolution(), d: (() => { const g = ol.proj.transform([18.0807, 44.73045], 'EPSG:4326', map.getView().getProjection()), v = map.getView().getCenter(); return Math.hypot(g[0] - v[0], g[1] - v[1]); })(), t1: document.querySelector('#kgrs .t1').innerText, chips: document.querySelector('#kgrs .chips').innerText }));
console.log(JSON.stringify(st));
note(st.on && /run/.test(st.go), 'GPS se pokrece sam');
note(st.d < 6 && st.res < 0.45 && st.res > 0.3, 'mapa fokusirana na korisnika, razmjer ' + st.res);
note(/8,0 m do najbliže granice parcele/.test(st.st) && /Pozicija prikazana/.test(st.st), 'udaljenost do granice iznad "Pozicija prikazana": ' + st.st);
note(/715/.test(st.chips) && /Njiva/.test(st.chips), 'parcela ispod nas: površina i vrsta u panelu: ' + st.chips);
await p.screenshot({ path: 'mapopen.png' });
await p.evaluate(() => { const st = document.createElement('style'); st.id = 'hidedot'; st.textContent = '.kgrs-me-dot{display:none!important}'; document.head.appendChild(st); });
await p.waitForTimeout(3200);
const fb = await p.evaluate(() => map.getLayers().getArray().some(l => l.getSource && l.getSource().getFeatures && l.getSource().getFeatures().some(f => f.get('k') === 'me')));
note(fb, 'ako DOM oznaka nije vidljiva, pozicija se crta na mapi (rezerva)');
await p.evaluate(() => document.getElementById('hidedot').remove());
console.log('2b) VLASNICI: automatsko popunjavanje');
geo.features[0].properties = { POVRSINA: '715', KULTURA: 'Njiva 3. klase', KO: '20012', LOKACIJA: '34', KT: '512/1' };
await p.evaluate(() => { document.getElementById('ddlPP').addEventListener('change', () => setTimeout(() => { document.getElementById('ddlKO').innerHTML = '<option value="">KO</option><option value="20012">Доња Пакленица</option><option value="20013">Фоча</option>'; }, 100)); });
await p.mouse.click(190, 500); await p.waitForTimeout(2500);
await p.evaluate(() => { const b = [...document.querySelectorAll('#kgrs .detail .chip-btn')].find(x => /Vlasnici/.test(x.innerText)); if (b) b.click(); }); await p.waitForTimeout(4500);
const f = await p.evaluate(() => ({ num: document.getElementById('i_parc').value, pp: document.getElementById('ddlPP').value, ko: document.getElementById('ddlKO').value, kotxt: (document.querySelector('#ddlKO').closest('.ui.dropdown').querySelector(':scope > .text') || {}).innerText, kodef: !!document.querySelector('#ddlKO').closest('.ui.dropdown').querySelector(':scope > .text.default'), on: document.getElementById('kgrs').classList.contains('on') }));
console.log(JSON.stringify(f));
note(f.num === '512/1' && f.pp === '34' && f.ko === '20012' && /Пакленица/.test(f.kotxt) && !f.kodef && !f.on, 'Vlasnici popunjava broj, opštinu i KO (po šifri) sam: ' + JSON.stringify(f));
await p.screenshot({ path: 'owners.png' });
await p.click('#kgrs-mapbtn'); await p.waitForTimeout(2500);
console.log('3) POMJERANJE JEDNIM PRSTOM');
const cdp = await ctx.newCDPSession(p);
const ctr = () => p.evaluate(() => map.getView().getCenter().slice());
const drag = async (x0, y0, x1, y1) => { const pt = (x, y) => [{ x, y }];
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: pt(x0, y0) });
  for (let i = 1; i <= 10; i++) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: pt(x0 + (x1 - x0) * i / 10, y0 + (y1 - y0) * i / 10) });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await p.waitForTimeout(700); };
const c0 = await ctr(); await drag(220, 330, 120, 260); const c1 = await ctr();
note(Math.hypot(c1[0] - c0[0], c1[1] - c0[1]) > 3, 'jedan prst pomjera mapu (' + Math.round(Math.hypot(c1[0] - c0[0], c1[1] - c0[1])) + ')');
note(await p.evaluate(() => getComputedStyle(document.querySelector('#kgrsmap .ol-viewport')).touchAction === 'none'), 'touch-action: none na mapi');
// njihov DragPan sa uslovom (dva prsta / Ctrl) ne smije blokirati
note(await p.evaluate(() => map.getInteractions().getArray().filter(i => i instanceof ol.interaction.DragPan).length === 1), 'tacno jedan DragPan');
await p.click('#kgrs .top .rb'); await p.waitForTimeout(1300);
const af = await p.evaluate(() => ({ on: document.getElementById('kgrs').classList.contains('on'), dp: map.getInteractions().getArray().filter(i => i instanceof ol.interaction.DragPan).length, hero: getComputedStyle(document.getElementById('kgrs-mapbtn')).display }));
note(!af.on && af.dp === 1 && af.hero !== 'none', 'zatvaranje vraca pocetnu i njihov DragPan: ' + JSON.stringify(af));
note(p.errs.length === 0, 'bez JS gresaka ' + p.errs.join(';'));
console.log('\nUKUPNO PROBLEMA:', fails.length); fails.forEach(f => console.log(' -', f));
await b.close(); srv.close();
