name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          with:
  host: 77.42.82.177
  username: ratko
  key: ${{ secrets.SSH_KEY }}
  port: 22
  script_stop: true
  debug: true
