name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 77.42.82.177
          username: ratko
          key_path: key.pem
          port: 22
          script_stop: true
          debug: true
          script: |
            cd /var/www/app
            git pull origin main
            pm2 restart app.js
